name: Deploy Infrastructure to AWS

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.TF_REGION }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_VAR_region:                ${{ secrets.TF_REGION }}
  TF_VAR_eks_cluster_name:     ${{ secrets.TF_EKS_CLUSTER_NAME }}
  TF_VAR_ecr_name:             ${{ secrets.TF_ECR_NAME }}

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.3"
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: aws-terraform/
        run: terraform init

      - name: Terraform Validate
        working-directory: aws-terraform/
        run: terraform validate

      - name: Terraform Plan
        working-directory: aws-terraform/
        run: terraform plan -no-color

      - name: Terraform Apply
        working-directory: aws-terraform/
        run: terraform apply -auto-approve -no-color

      - name: Export Terraform Outputs
        working-directory: aws-terraform/
        run: |
          echo "ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url)" > tf_outputs.env
          echo "EKS_CLUSTER_NAME=$(terraform output -raw eks_cluster_name)" >> tf_outputs.env
          echo "REGION=$(terraform output -raw region)" >> tf_outputs.env

      - name: Upload Terraform Outputs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: aws-terraform/tf_outputs.env
          retention-days: 1
          overwrite: true