name: Destroy Infrastructure

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.TF_REGION }}

  TF_VAR_region:                ${{ secrets.TF_REGION }}
  TF_VAR_resource_group_name:  ${{ secrets.TF_RG_NAME }}
  TF_VAR_eks_cluster_name:     ${{ secrets.TF_EKS_CLUSTER_NAME }}
  TF_VAR_ecr_name:             ${{ secrets.TF_ECR_NAME }}
  TF_VAR_secrets_manager_name: ${{ secrets.TF_SECRET_NAME }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.3"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve