name: Destroy AWS Infrastructure Only Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: ${{ secrets.TF_REGION }}
  TF_VAR_region: ${{ secrets.TF_REGION }}
  TF_VAR_eks_cluster_name: ${{ secrets.TF_EKS_CLUSTER_NAME }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.3"

      - name: Terraform Init
        id: init
        working-directory: aws-terraform/
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        working-directory: aws-terraform/
        run: terraform destroy -lock=false -auto-approve